import { createTree } from "@/lib/graph";

export const dribblingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: [
        { attributeName: "agility", updateValue: 1 },
        { attributeName: "dribbling", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "agility", updateValue: 1 }],
    },
    {
      activationCost: 3,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: [
        { attributeName: "agility", updateValue: 2 },
        { attributeName: "dribbling", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "dribbling", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: [
        { attributeName: "agility", updateValue: 1 },
        { attributeName: "positioning", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: [
        { attributeName: "positioning", updateValue: 2 },
        { attributeName: "dribbling", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: [
        { attributeName: "positioning", updateValue: 2 },
        { attributeName: "dribbling", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "agility", updateValue: 2 }],
    },
    {
      activationCost: 5,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "skillMoves", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "dribbling", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "agility", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "agility", updateValue: 2 },
        { attributeName: "dribbling", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "dribbling", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      modifiers: [
        { attributeName: "agility", updateValue: 2 },
        { attributeName: "dribbling", updateValue: 2 },
      ],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: [
        { attributeName: "balance", updateValue: 1 },
        { attributeName: "ballControl", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "ballControl", updateValue: 1 }],
    },
    {
      activationCost: 3,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: [
        { attributeName: "balance", updateValue: 2 },
        { attributeName: "ballControl", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "balance", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: [
        { attributeName: "positioning", updateValue: 3 },
        { attributeName: "ballControl", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: [
        { attributeName: "positioning", updateValue: 2 },
        { attributeName: "ballControl", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: [
        { attributeName: "balance", updateValue: 2 },
        { attributeName: "positioning", updateValue: 3 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "ballControl", updateValue: 2 }],
    },
    {
      activationCost: 5,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "skillMoves", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "balance", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "ballControl", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "balance", updateValue: 4 },
        { attributeName: "ballControl", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "balance", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      modifiers: [
        { attributeName: "balance", updateValue: 3 },
        { attributeName: "ballControl", updateValue: 2 },
      ],
    },
  ]),
];
