import { createTree } from "@/lib/graph";

export const dribblingTrees = [
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: new Map([
        ["agility", 1],
        ["dribbling", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 0,
      modifiers: new Map([["agility", 1]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: new Map([
        ["agility", 2],
        ["dribbling", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      modifiers: new Map([["dribbling", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: new Map([
        ["agility", 1],
        ["positioning", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: new Map([
        ["positioning", 2],
        ["dribbling", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: new Map([
        ["positioning", 2],
        ["dribbling", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["agility", 2]]),
    },
    {
      baseActivationCost: 5,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([["skillMoves", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["dribbling", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["agility", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["agility", 2],
        ["dribbling", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["dribbling", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      modifiers: new Map([
        ["agility", 2],
        ["dribbling", 2],
      ]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: new Map([
        ["balance", 1],
        ["ballControl", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 0,
      modifiers: new Map([["ballControl", 1]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: new Map([
        ["balance", 2],
        ["ballControl", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      modifiers: new Map([["balance", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: new Map([
        ["positioning", 3],
        ["ballControl", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: new Map([
        ["positioning", 2],
        ["ballControl", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: new Map([
        ["balance", 2],
        ["positioning", 3],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["ballControl", 2]]),
    },
    {
      baseActivationCost: 5,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([["skillMoves", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["balance", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["ballControl", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["balance", 4],
        ["ballControl", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["balance", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      modifiers: new Map([
        ["balance", 3],
        ["ballControl", 2],
      ]),
    },
  ]),
];
