import { createTree } from "@/lib/graph";

export const goalkeepingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "gkDiving", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "gkReflexes", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "gkDiving", updateValue: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "gkPositioning", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "gkReflexes", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "gkDiving", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: [{ attributeName: "gkPositioning", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "gkReflexes", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "gkDiving", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "gkPositioning", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "gkReflexes", updateValue: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "gkDiving", updateValue: 3 }],
    },
    {
      activationCost: 5,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "gkDiving", updateValue: 3 },
        { attributeName: "gkReflexes", updateValue: 3 },
      ],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "gkReflexes", updateValue: 3 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "gkKicking", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "gkHandling", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "gkKicking", updateValue: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "gkPositioning", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "gkHandling", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "gkKicking", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: [{ attributeName: "gkPositioning", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "gkHandling", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "gkKicking", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "gkPositioning", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "gkHandling", updateValue: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "gkKicking", updateValue: 3 }],
    },
    {
      activationCost: 5,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "gkHandling", updateValue: 4 },
        { attributeName: "gkKicking", updateValue: 3 },
      ],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "gkHandling", updateValue: 4 }],
    },
  ]),
];
