import { createTree } from "@/lib/graph";

export const goalkeepingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "gkDiving", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "gkReflexes", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "gkDiving", value: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "gkPositioning", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "gkReflexes", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "gkDiving", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      actions: [{ attribute: "gkPositioning", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "gkReflexes", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "gkDiving", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "gkPositioning", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "gkReflexes", value: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "gkDiving", value: 3 }],
    },
    {
      activationCost: 5,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      actions: [
        { attribute: "gkDiving", value: 3 },
        { attribute: "gkReflexes", value: 3 },
      ],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "gkReflexes", value: 3 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "gkKicking", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "gkHandling", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "gkKicking", value: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "gkPositioning", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "gkHandling", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "gkKicking", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      actions: [{ attribute: "gkPositioning", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "gkHandling", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "gkKicking", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "gkPositioning", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "gkHandling", value: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "gkKicking", value: 3 }],
    },
    {
      activationCost: 5,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      actions: [
        { attribute: "gkHandling", value: 4 },
        { attribute: "gkKicking", value: 3 },
      ],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "gkHandling", value: 4 }],
    },
  ]),
];
