import { createTree } from "@/lib/graph";

export const goalkeepingTrees = [
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["gkDiving", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["gkReflexes", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: new Map([["gkDiving", 2]]),
    },
    {
      baseActivationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: new Map([["gkPositioning", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["gkReflexes", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: new Map([["gkDiving", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: new Map([["gkPositioning", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["gkReflexes", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["gkDiving", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([["gkPositioning", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["gkReflexes", 3]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["gkDiving", 3]]),
    },
    {
      baseActivationCost: 5,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["gkDiving", 3],
        ["gkReflexes", 3],
      ]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["gkReflexes", 3]]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["gkKicking", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["gkHandling", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: new Map([["gkKicking", 2]]),
    },
    {
      baseActivationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: new Map([["gkPositioning", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["gkHandling", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: new Map([["gkKicking", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: new Map([["gkPositioning", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["gkHandling", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["gkKicking", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([["gkPositioning", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["gkHandling", 3]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["gkKicking", 3]]),
    },
    {
      baseActivationCost: 5,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["gkHandling", 4],
        ["gkKicking", 3],
      ]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["gkHandling", 4]]),
    },
  ]),
];
