import { createTree } from "@/lib/graph";

export const passingTrees = [
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["crossing", 1]]),
    },
    {
      baseActivationCost: 3,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["curve", 1]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: new Map([["crossing", 3]]),
    },
    {
      baseActivationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: new Map([["vision", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["curve", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: new Map([["crossing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: new Map([["vision", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["curve", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      modifiers: new Map([["crossing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      modifiers: new Map([["vision", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["curve", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["crossing", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["crossing", 2],
        ["curve", 3],
      ]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["curve", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A5"],
      row: 5,
      column: 0,
      modifiers: new Map([["crossing", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["C5"],
      row: 5,
      column: 0,
      modifiers: new Map([["curve", 3]]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["shortPassing", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["longPassing", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: new Map([["shortPassing", 2]]),
    },
    {
      baseActivationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: new Map([["vision", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["longPassing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: new Map([["shortPassing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: new Map([["vision", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["longPassing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      modifiers: new Map([["shortPassing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      modifiers: new Map([["vision", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["longPassing", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["shortPassing", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["longPassing", 2],
        ["shortPassing", 3],
      ]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["longPassing", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A5"],
      row: 5,
      column: 0,
      modifiers: new Map([["shortPassing", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["C5"],
      row: 5,
      column: 0,
      modifiers: new Map([["longPassing", 3]]),
    },
  ]),
];
