import { createTree } from "@/lib/graph";

export const passingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "crossing", value: 1 }],
    },
    {
      activationCost: 3,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "curve", value: 1 }],
    },
    {
      activationCost: 3,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "crossing", value: 3 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "vision", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "curve", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "crossing", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      actions: [{ attribute: "vision", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "curve", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "crossing", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "vision", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "curve", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "crossing", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 1,
      actions: [
        { attribute: "crossing", value: 2 },
        { attribute: "curve", value: 3 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "curve", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A5"],
      row: 5,
      column: 0,
      actions: [{ attribute: "crossing", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C5"],
      row: 5,
      column: 0,
      actions: [{ attribute: "curve", value: 3 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "shortPassing", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "longPassing", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "shortPassing", value: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "vision", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "longPassing", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "shortPassing", value: 2 }], //awdadwada
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      actions: [{ attribute: "vision", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "longPassing", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "shortPassing", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "vision", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "longPassing", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "shortPassing", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 1,
      actions: [
        { attribute: "longPassing", value: 2 },
        { attribute: "shortPassing", value: 3 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "longPassing", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A5"],
      row: 5,
      column: 0,
      actions: [{ attribute: "shortPassing", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C5"],
      row: 5,
      column: 0,
      actions: [{ attribute: "longPassing", value: 3 }],
    },
  ]),
];
