import { createTree } from "@/lib/graph";

export const passingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "crossing", updateValue: 1 }],
    },
    {
      activationCost: 3,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "curve", updateValue: 1 }],
    },
    {
      activationCost: 3,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "crossing", updateValue: 3 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "vision", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "curve", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "crossing", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: [{ attributeName: "vision", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "curve", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "crossing", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "vision", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "curve", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "crossing", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "crossing", updateValue: 2 },
        { attributeName: "curve", updateValue: 3 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "curve", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A5"],
      row: 5,
      column: 0,
      modifiers: [{ attributeName: "crossing", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C5"],
      row: 5,
      column: 0,
      modifiers: [{ attributeName: "curve", updateValue: 3 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "shortPassing", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "longPassing", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "shortPassing", updateValue: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "vision", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "longPassing", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "shortPassing", updateValue: 2 }], //awdadwada
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 1,
      modifiers: [{ attributeName: "vision", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2", "C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "longPassing", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "shortPassing", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "vision", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "longPassing", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "shortPassing", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "longPassing", updateValue: 2 },
        { attributeName: "shortPassing", updateValue: 3 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "longPassing", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A5"],
      row: 5,
      column: 0,
      modifiers: [{ attributeName: "shortPassing", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C5"],
      row: 5,
      column: 0,
      modifiers: [{ attributeName: "longPassing", updateValue: 3 }],
    },
  ]),
];
