import { createTree } from "@/lib/graph";

export const physicalityTrees = [
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: new Map([["strength", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["aggression", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: new Map([["strength", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["aggression", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 0,
      modifiers: new Map([["strength", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 1,
      modifiers: new Map([
        ["strength", 1],
        ["aggression", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["aggression", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["strength", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([
        ["strength", 2],
        ["aggression", 3],
      ]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["aggression", 2]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      modifiers: new Map([
        ["strength", 2],
        ["aggression", 3],
      ]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["jumping", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: new Map([["stamina", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: new Map([["jumping", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: new Map([["stamina", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 0,
      modifiers: new Map([["jumping", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 1,
      modifiers: new Map([
        ["jumping", 1],
        ["stamina", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 2,
      modifiers: new Map([["stamina", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["jumping", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([
        ["jumping", 2],
        ["stamina", 2],
      ]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["stamina", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 0,
      modifiers: new Map([["jumping", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["stamina", 3]]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["composure", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["reactions", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: new Map([["composure", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["reactions", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 0,
      modifiers: new Map([["composure", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 1,
      modifiers: new Map([
        ["reactions", 3],
        ["composure", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["reactions", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      modifiers: new Map([["composure", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["B3"],
      row: 3,
      column: 2,
      modifiers: new Map([["reactions", 4]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      modifiers: new Map([["composure", 2]]),
    },
  ]),
];
