import { createTree } from "@/lib/graph";

export const physicalityTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: [{ attributeName: "strength", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "aggression", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "strength", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "aggression", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "strength", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 1,
      modifiers: [
        { attributeName: "strength", updateValue: 1 },
        { attributeName: "aggression", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "aggression", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "strength", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [
        { attributeName: "strength", updateValue: 2 },
        { attributeName: "aggression", updateValue: 3 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "aggression", updateValue: 2 }],
    },
    {
      activationCost: 4,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      modifiers: [
        { attributeName: "strength", updateValue: 2 },
        { attributeName: "aggression", updateValue: 3 },
      ],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "jumping", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: [{ attributeName: "stamina", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "jumping", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "stamina", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "jumping", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 1,
      modifiers: [
        { attributeName: "jumping", updateValue: 1 },
        { attributeName: "stamina", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "stamina", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "jumping", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [
        { attributeName: "jumping", updateValue: 2 },
        { attributeName: "stamina", updateValue: 2 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "stamina", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "jumping", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "stamina", updateValue: 3 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "composure", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "reactions", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "composure", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "reactions", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "composure", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 1,
      modifiers: [
        { attributeName: "reactions", updateValue: 3 },
        { attributeName: "composure", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "reactions", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "composure", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["B3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "reactions", updateValue: 4 }],
    },
    {
      activationCost: 2,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      modifiers: [{ attributeName: "composure", updateValue: 2 }],
    },
  ]),
];
