import { createTree } from "@/lib/graph";

export const physicalityTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      actions: [{ attribute: "strength", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "aggression", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "strength", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "aggression", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "strength", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 1,
      actions: [
        { attribute: "strength", value: 1 },
        { attribute: "aggression", value: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["B2", "C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "aggression", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "strength", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      actions: [
        { attribute: "strength", value: 2 },
        { attribute: "aggression", value: 3 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "aggression", value: 2 }],
    },
    {
      activationCost: 4,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      actions: [
        { attribute: "strength", value: 2 },
        { attribute: "aggression", value: 3 },
      ],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "jumping", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      actions: [{ attribute: "stamina", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "jumping", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "stamina", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "jumping", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 1,
      actions: [
        { attribute: "jumping", value: 1 },
        { attribute: "stamina", value: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "B2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "stamina", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "jumping", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 1,
      actions: [
        { attribute: "jumping", value: 2 },
        { attribute: "stamina", value: 2 },
      ],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "B3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "stamina", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "jumping", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "stamina", value: 3 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "composure", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "reactions", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "composure", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "reactions", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "composure", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 1,
      actions: [
        { attribute: "reactions", value: 3 },
        { attribute: "composure", value: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A2", "C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "reactions", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "composure", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["B3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "reactions", value: 4 }],
    },
    {
      activationCost: 2,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      actions: [{ attribute: "composure", value: 2 }],
    },
  ]),
];
