import { createTree } from "@/lib/graph";

export const shootingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "freeKickAccuracy", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: [],
      row: 0,
      column: 1,
      actions: [{ attribute: "weakFoot", value: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "penalties", value: 3 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "freeKickAccuracy", value: 2 }],
    },
    {
      activationCost: 5,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "weakFoot", value: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "penalties", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "freeKickAccuracy", value: 2 }],
    },
    {
      activationCost: 10,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      actions: [{ attribute: "weakFoot", value: 1 }],
    },
    {
      activationCost: 3,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "penalties", value: 4 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "freeKickAccuracy", value: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "freeKickAccuracy", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "penalties", value: 5 }],
    },
    {
      activationCost: 4,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      actions: [{ attribute: "freeKickAccuracy", value: 5 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "headingAccuracy", value: 2 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      actions: [{ attribute: "finishing", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "headingAccuracy", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      actions: [{ attribute: "finishing", value: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "volleys", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "headingAccuracy", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      actions: [{ attribute: "finishing", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "volleys", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "headingAccuracy", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3", "C3"],
      row: 3,
      column: 1,
      actions: [{ attribute: "finishing", value: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "volleys", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "headingAccuracy", value: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      actions: [{ attribute: "finishing", value: 4 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "volleys", value: 4 }],
    },
    {
      activationCost: 4,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      actions: [
        { attribute: "volleys", value: 3 },
        { attribute: "headingAccuracy", value: 2 },
      ],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      actions: [{ attribute: "shotPower", value: 2 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      actions: [{ attribute: "longShots", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      actions: [{ attribute: "shotPower", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      actions: [
        { attribute: "shotPower", value: 1 },
        { attribute: "longShots", value: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      actions: [{ attribute: "longShots", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      actions: [{ attribute: "shotPower", value: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      actions: [{ attribute: "longShots", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 0,
      actions: [{ attribute: "shotPower", value: 2 }],
    },
    {
      activationCost: 4,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 1,
      actions: [
        { attribute: "shotPower", value: 2 },
        { attribute: "longShots", value: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 2,
      actions: [{ attribute: "longShots", value: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 0,
      actions: [{ attribute: "shotPower", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 1,
      actions: [{ attribute: "shotPower", value: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C4"],
      row: 4,
      column: 2,
      actions: [{ attribute: "longShots", value: 3 }],
    },
  ]),
];
