import { createTree } from "@/lib/graph";

export const shootingTrees = [
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["freeKickAccuracy", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: new Map([["weakFoot", 1]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["penalties", 3]]),
    },
    {
      baseActivationCost: 1,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: new Map([["freeKickAccuracy", 2]]),
    },
    {
      baseActivationCost: 5,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: new Map([["weakFoot", 1]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["penalties", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: new Map([["freeKickAccuracy", 2]]),
    },
    {
      baseActivationCost: 10,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: new Map([["weakFoot", 1]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["penalties", 4]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["freeKickAccuracy", 3]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([["freeKickAccuracy", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["penalties", 5]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      modifiers: new Map([["freeKickAccuracy", 5]]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["headingAccuracy", 2]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: new Map([["finishing", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: new Map([["headingAccuracy", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: new Map([["finishing", 2]]),
    },
    {
      baseActivationCost: 1,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      modifiers: new Map([["volleys", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: new Map([["headingAccuracy", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: new Map([["finishing", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["volleys", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      modifiers: new Map([["headingAccuracy", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([["finishing", 3]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["B3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["volleys", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: new Map([["headingAccuracy", 3]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: new Map([["finishing", 4]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["volleys", 4]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      modifiers: new Map([
        ["volleys", 3],
        ["headingAccuracy", 2],
      ]),
    },
  ]),
  createTree([
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: new Map([["shotPower", 2]]),
    },
    {
      baseActivationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: new Map([["longShots", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: new Map([["shotPower", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: new Map([
        ["shotPower", 1],
        ["longShots", 1],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: new Map([["longShots", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: new Map([["shotPower", 2]]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: new Map([["longShots", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 0,
      modifiers: new Map([["shotPower", 2]]),
    },
    {
      baseActivationCost: 4,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 1,
      modifiers: new Map([
        ["shotPower", 2],
        ["longShots", 2],
      ]),
    },
    {
      baseActivationCost: 2,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 2,
      modifiers: new Map([["longShots", 2]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 0,
      modifiers: new Map([["shotPower", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 1,
      modifiers: new Map([["shotPower", 3]]),
    },
    {
      baseActivationCost: 3,
      parentIds: ["C4"],
      row: 4,
      column: 2,
      modifiers: new Map([["longShots", 3]]),
    },
  ]),
];
