import { createTree } from "@/lib/graph";

export const shootingTrees = [
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "freeKickAccuracy", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: [{ attributeName: "weakFoot", updateValue: 1 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "penalties", updateValue: 3 }],
    },
    {
      activationCost: 1,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "freeKickAccuracy", updateValue: 2 }],
    },
    {
      activationCost: 5,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "weakFoot", updateValue: 1 }],
    },
    {
      activationCost: 2,
      parentIds: ["C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "penalties", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "freeKickAccuracy", updateValue: 2 }],
    },
    {
      activationCost: 10,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: [{ attributeName: "weakFoot", updateValue: 1 }],
    },
    {
      activationCost: 3,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "penalties", updateValue: 4 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "freeKickAccuracy", updateValue: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "freeKickAccuracy", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "penalties", updateValue: 5 }],
    },
    {
      activationCost: 4,
      parentIds: ["B4"],
      row: 4,
      column: 1,
      modifiers: [{ attributeName: "freeKickAccuracy", updateValue: 5 }],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "headingAccuracy", updateValue: 2 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 1,
      modifiers: [{ attributeName: "finishing", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "headingAccuracy", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["B1"],
      row: 1,
      column: 1,
      modifiers: [{ attributeName: "finishing", updateValue: 2 }],
    },
    {
      activationCost: 1,
      parentIds: ["B1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "volleys", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "headingAccuracy", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["B2"],
      row: 2,
      column: 1,
      modifiers: [{ attributeName: "finishing", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "volleys", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "headingAccuracy", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3", "C3"],
      row: 3,
      column: 1,
      modifiers: [{ attributeName: "finishing", updateValue: 3 }],
    },
    {
      activationCost: 2,
      parentIds: ["B3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "volleys", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "headingAccuracy", updateValue: 3 }],
    },
    {
      activationCost: 4,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 1,
      modifiers: [{ attributeName: "finishing", updateValue: 4 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4", "B4", "C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "volleys", updateValue: 4 }],
    },
    {
      activationCost: 4,
      parentIds: ["B5"],
      row: 5,
      column: 1,
      modifiers: [
        { attributeName: "volleys", updateValue: 3 },
        { attributeName: "headingAccuracy", updateValue: 2 },
      ],
    },
  ]),
  createTree([
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 0,
      modifiers: [{ attributeName: "shotPower", updateValue: 2 }],
    },
    {
      activationCost: 1,
      parentIds: [],
      row: 0,
      column: 2,
      modifiers: [{ attributeName: "longShots", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 0,
      modifiers: [{ attributeName: "shotPower", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 1,
      modifiers: [
        { attributeName: "shotPower", updateValue: 1 },
        { attributeName: "longShots", updateValue: 1 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A1", "C1"],
      row: 1,
      column: 2,
      modifiers: [{ attributeName: "longShots", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["A2"],
      row: 2,
      column: 0,
      modifiers: [{ attributeName: "shotPower", updateValue: 2 }],
    },
    {
      activationCost: 2,
      parentIds: ["C2"],
      row: 2,
      column: 2,
      modifiers: [{ attributeName: "longShots", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 0,
      modifiers: [{ attributeName: "shotPower", updateValue: 2 }],
    },
    {
      activationCost: 4,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 1,
      modifiers: [
        { attributeName: "shotPower", updateValue: 2 },
        { attributeName: "longShots", updateValue: 2 },
      ],
    },
    {
      activationCost: 2,
      parentIds: ["A3", "C3"],
      row: 3,
      column: 2,
      modifiers: [{ attributeName: "longShots", updateValue: 2 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 0,
      modifiers: [{ attributeName: "shotPower", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["A4"],
      row: 4,
      column: 1,
      modifiers: [{ attributeName: "shotPower", updateValue: 3 }],
    },
    {
      activationCost: 3,
      parentIds: ["C4"],
      row: 4,
      column: 2,
      modifiers: [{ attributeName: "longShots", updateValue: 3 }],
    },
  ]),
];
